### ISSUE TITLE
블로그 댓글 기능 추가해주세요ㅎㅎ

### ISSUE THREAD

**Issue by gimdongwon** [dev4us/dev4us.github.io#1]
좋은 글이 많네요~ ㅎㅎ 댓글 달고 싶은데 댓글 기능이 없어서 아쉽 ㅜㅜ

https://devmjun.github.io/archive/addComments

ps : hls post, 렌더링 post 잘 읽었습니다 😀

**Comment by dev4us** [comment]
ㅠㅠ 디스커스로 댓글을 넣었었다가 뺐어요..
광고도 광고인데 불편러들이 많아서..
죄송해요 그래서 메일로만 소통하고 있습니다..

**Comment by gimdongwon** [comment]
헐 왠지 ㅜㅜ 그런 히스토리가 있었군요 ㅎㅎ 알겠습니다~
